//! The fixture is generated by the editor from synthetic asset definitions.
//! No datadir, level records, profiles or sprite banks are mounted.
use robin_engine::engine::{Engine, EngineArgs, LevelAssets, LevelLoadArgs, SimConfig};
use robin_engine::level_data::LoadedLevel;

#[test]
fn editor_asset_masks_construct_baked_coverage_and_local_state_links() {
    let mut assets = LevelAssets::new();
    let engine = construct(
        include_bytes!("fixtures/asset-mask.level.json"),
        &mut assets,
    );
    let grid = engine.fast_grid();
    assert_eq!(grid.level.masks.len(), 2);
    assert_eq!(grid.level.masks[0].mask_type, 23);
    assert_eq!(
        (grid.level.masks[0].width, grid.level.masks[0].height),
        (10, 40)
    );
    assert_eq!(
        (grid.level.masks[1].width, grid.level.masks[1].height),
        (10, 10)
    );
    assert!(
        grid.level
            .masks
            .iter()
            .all(|mask| mask.bitmap.iter().all(|&pixel| pixel == 1))
    );
    assert_eq!(grid.mask_active, [true, false]);
    let mask = &grid.level.masks[0];
    use robin_engine::coordinates::{MapPoint, WorldPoint3D};
    assert!(mask.is_applied_to_point_character(MapPoint::new(345., 339.)));
    assert!(!mask.is_applied_to_point_character(MapPoint::new(345., 351.)));
    let obstacles = robin_engine::sight_obstacle::ObstacleList::from_slice_all_active(
        &assets.environment.static_sight_obstacles,
    );
    assert!(mask.is_applied_to_point_3d(
        WorldPoint3D {
            x: 345.,
            y: 345.,
            z: 20.
        },
        false,
        obstacles
    ));
    assert!(!mask.is_applied_to_point_3d(
        WorldPoint3D {
            x: 345.,
            y: 345.,
            z: 40.
        },
        false,
        obstacles
    ));
}

fn descriptor_with_compiled_masks() -> serde_json::Value {
    let mut descriptor: serde_json::Value =
        serde_json::from_slice(include_bytes!("fixtures/asset-lift.level.json")).unwrap();
    let mask = serde_json::json!({
        "layer": 0, "mask_type": 1,
        "character_polyline": [[300, 320], [309, 320]],
        "projectile_polyline": null,
        "box_top_left": [300, 300], "box_size": [9, 2],
        "mask_data": [3, 2, 170, 128, 0], "obstacle_indices": []
    });
    let mut upper = mask.clone();
    upper["layer"] = 1.into();
    upper["mask_type"] = 4.into();
    upper["character_polyline"] = serde_json::Value::Null;
    let mut projectile = mask.clone();
    projectile["mask_type"] = 18.into();
    projectile["character_polyline"] = serde_json::Value::Null;
    projectile["projectile_polyline"] = serde_json::json!([]);
    projectile["obstacle_indices"] = serde_json::json!([0]);
    descriptor["asset_geometry"]["masks"] = serde_json::json!([mask, upper, projectile]);
    descriptor
}

#[test]
fn editor_encoded_mask_bitmaps_decode_to_the_complete_baked_silhouette() {
    #[derive(serde::Serialize, serde::Deserialize)]
    struct Case {
        width: u16,
        height: u16,
        pixels: String,
        encoded: Vec<u8>,
    }
    let cases: Vec<Case> =
        serde_json::from_slice(include_bytes!("fixtures/compiled-mask-bitmaps.json")).unwrap();
    for case in cases {
        let expected = case
            .pixels
            .bytes()
            .map(|pixel| pixel - b'0')
            .collect::<Vec<_>>();
        assert_eq!(
            robin_engine::mask::decode_mask_bitmap(&case.encoded, case.width, case.height),
            expected
        );
    }
}

#[test]
fn compiled_masks_construct_typed_bitmaps_and_per_layer_indices() {
    use robin_engine::coordinates::{MapPoint, WorldPoint3D};
    let descriptor = descriptor_with_compiled_masks();
    let mut assets = LevelAssets::new();
    let engine = construct(&serde_json::to_vec(&descriptor).unwrap(), &mut assets);
    let grid = engine.fast_grid();
    assert_eq!(grid.level.masks.len(), 3);
    assert_eq!(
        grid.level.layers[0]
            .mask_indices
            .iter()
            .map(|&i| usize::from(i))
            .collect::<Vec<_>>(),
        [0, 2]
    );
    assert_eq!(
        grid.level.layers[1]
            .mask_indices
            .iter()
            .map(|&i| usize::from(i))
            .collect::<Vec<_>>(),
        [1]
    );
    let character = &grid.level.masks[0];
    assert_eq!(
        character.bitmap,
        [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    );
    assert!(character.is_applied_to_point_character(MapPoint::new(304., 319.)));
    assert!(!character.is_applied_to_point_character(MapPoint::new(304., 320.)));
    assert_eq!(
        grid.level.masks[1].mask_type,
        robin_engine::level_data::MASK_VIEW
    );
    let obstacle = &assets.environment.static_sight_obstacles[0];
    let x = obstacle.obstacle_points.iter().map(|p| p.x).sum::<f32>()
        / obstacle.obstacle_points.len() as f32;
    let y = obstacle.obstacle_points.iter().map(|p| p.y).sum::<f32>()
        / obstacle.obstacle_points.len() as f32;
    let obstacles = robin_engine::sight_obstacle::ObstacleList::from_slice_all_active(
        &assets.environment.static_sight_obstacles,
    );
    let mask = &grid.level.masks[2];
    assert!(mask.is_applied_to_point_3d(
        WorldPoint3D {
            x,
            y,
            z: obstacle.compute_top_z(x, y) - 1.
        },
        false,
        obstacles
    ));
    assert!(!mask.is_applied_to_point_3d(
        WorldPoint3D {
            x,
            y,
            z: obstacle.compute_top_z(x, y) + 1.
        },
        false,
        obstacles
    ));
}

#[test]
fn compiled_masks_reject_unresolved_links_invalid_types_and_malformed_bitmaps() {
    let descriptor = descriptor_with_compiled_masks();
    for (field, value) in [
        ("layer", serde_json::json!(99)),
        ("mask_type", serde_json::json!(0)),
        ("mask_type", serde_json::json!(8)),
        ("mask_type", serde_json::json!(16)),
        ("character_polyline", serde_json::json!(null)),
        (
            "character_polyline",
            serde_json::json!([[309, 320], [300, 320]]),
        ),
        ("box_size", serde_json::json!([0, 2])),
        ("box_top_left", serde_json::json!([32760, 300])),
        ("mask_data", serde_json::json!([3, 2, 170])),
        ("mask_data", serde_json::json!([2, 131, 255, 0])),
        ("obstacle_indices", serde_json::json!([999])),
    ] {
        let mut bad = descriptor.clone();
        bad["asset_geometry"]["masks"][0][field] = value;
        let error = LoadedLevel::hackable_from_json(&serde_json::to_vec(&bad).unwrap())
            .err()
            .unwrap();
        assert!(error.contains("mask"), "{field}: {error}");
    }
    let mut missing_obstacle = descriptor.clone();
    missing_obstacle["asset_geometry"]["masks"][2]["obstacle_indices"] = serde_json::json!([999]);
    let error = LoadedLevel::hackable_from_json(&serde_json::to_vec(&missing_obstacle).unwrap())
        .err()
        .unwrap();
    assert!(error.contains("obstacle links"), "{error}");
}

#[test]
fn merged_platform_keeps_its_opening_without_an_invented_receiver() {
    use robin_engine::coordinates::MapPoint;
    use robin_engine::fast_find_grid::SectorIndex;
    use robin_engine::position_interface::SectorHandle;
    use robin_engine::sector::SectorNumber;
    let mut assets = LevelAssets::new();
    let engine = construct(
        include_bytes!("fixtures/asset-receiving-gap.level.json"),
        &mut assets,
    );
    let index = engine.fast_grid().level.sector_number_map[&SectorNumber::new(1)];
    let sector = SectorHandle::new(1)
        .unwrap()
        .with_arena_index(SectorIndex::new(index as u32).unwrap());
    assert!(
        engine
            .get_projection_area_index(&assets, sector, 1, MapPoint::new(350., 330.))
            .is_none()
    );
    for point in [MapPoint::new(350., 290.), MapPoint::new(390., 330.)] {
        let receiver = engine
            .get_projection_area_index(&assets, sector, 1, point)
            .unwrap();
        let obstacle = &assets.environment.static_sight_obstacles[usize::from(receiver)];
        assert_eq!(
            obstacle.compute_top_z_from_projection(point.x, point.y),
            20.
        );
    }
}

#[test]
fn authored_receiving_plane_survives_polygon_vertex_changes() {
    let mut descriptor: serde_json::Value = serde_json::from_slice(include_bytes!(
        "fixtures/asset-projection-material.level.json"
    ))
    .unwrap();
    let obstacle = &mut descriptor["asset_geometry"]["sight_obstacles"][0];
    for point in obstacle["points"].as_array_mut().unwrap() {
        let previous = point["z_top"].as_f64().unwrap();
        point["y"] = (point["y"].as_f64().unwrap() + 200.001 - previous).into();
        point["z_top"] = 200.001.into();
        point["z_bottom"] = 200.001.into();
    }
    let mut baseline_assets = LevelAssets::new();
    construct(
        &serde_json::to_vec(&descriptor).unwrap(),
        &mut baseline_assets,
    );
    let baseline = &baseline_assets.environment.static_sight_obstacles[0];
    let anchors = baseline.top_plane_points;
    descriptor["asset_geometry"]["sight_obstacles"][0]["projection_plane"] =
        serde_json::json!(anchors);
    descriptor["asset_geometry"]["sight_obstacles"][0]["points"]
        .as_array_mut()
        .unwrap()
        .rotate_left(1);
    let mut assets = LevelAssets::new();
    construct(&serde_json::to_vec(&descriptor).unwrap(), &mut assets);
    let receiver = &assets.environment.static_sight_obstacles[0];
    assert_eq!(receiver.top_plane_points, anchors);
    assert_eq!(receiver.bottom_plane_points, anchors);
    for x in 300..=400 {
        for y in 280..=380 {
            assert_eq!(
                receiver.compute_top_z_from_projection(x as f32, y as f32),
                baseline.compute_top_z_from_projection(x as f32, y as f32)
            );
        }
    }
    let mut invalid = descriptor.clone();
    invalid["asset_geometry"]["sight_obstacles"][0]["projection_plane"] =
        serde_json::json!([[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]]);
    assert!(
        LoadedLevel::hackable_from_json(&serde_json::to_vec(&invalid).unwrap())
            .err()
            .unwrap()
            .contains("receiving plane")
    );
    let mut invalid = descriptor.clone();
    invalid["asset_geometry"]["sight_obstacles"][0]["projection_plane"][0][2] = 201.into();
    assert!(
        LoadedLevel::hackable_from_json(&serde_json::to_vec(&invalid).unwrap())
            .err()
            .unwrap()
            .contains("receiving plane")
    );
    descriptor["asset_geometry"]["sight_obstacles"][0]["projection_area"] = serde_json::Value::Null;
    assert!(
        LoadedLevel::hackable_from_json(&serde_json::to_vec(&descriptor).unwrap())
            .err()
            .unwrap()
            .contains("receiving plane")
    );
}

#[derive(serde::Serialize, serde::Deserialize)]
struct ProjectionComparison {
    before: String,
    after: String,
    cases: Vec<ProjectionComparisonCase>,
}

#[derive(serde::Serialize, serde::Deserialize)]
struct ProjectionComparisonCase {
    before_sector: u16,
    after_sector: u16,
    layer: u16,
    bounds: [i32; 4],
}

#[derive(serde::Serialize, serde::Deserialize)]
struct ProjectionQueryReport {
    queries: usize,
    receiving: usize,
    height_differences: usize,
    material_differences: usize,
    coverage_differences: usize,
    maximum_height_difference: f32,
    first_differences: Vec<String>,
}

#[test]
#[ignore = "requires paired compiled descriptors via ROBIN_PROJECTION_COMPARISON"]
fn recovered_projection_partitions_preserve_sampled_runtime_queries() {
    use robin_engine::coordinates::MapPoint;
    use robin_engine::fast_find_grid::SectorIndex;
    use robin_engine::position_interface::SectorHandle;
    use robin_engine::sector::SectorNumber;

    let manifest_path = std::path::PathBuf::from(
        std::env::var("ROBIN_PROJECTION_COMPARISON").expect("comparison manifest"),
    );
    let manifest: ProjectionComparison =
        serde_json::from_slice(&std::fs::read(&manifest_path).unwrap()).unwrap();
    assert!(!manifest.cases.is_empty(), "no projection comparisons");
    let directory = manifest_path.parent().unwrap();
    let load = |file: &str, assets: &mut LevelAssets| {
        let bytes = std::fs::read(directory.join(file)).unwrap();
        let descriptor: serde_json::Value = serde_json::from_slice(&bytes).unwrap();
        let dimensions = &descriptor["walkable_polygon"][2];
        construct_with_dimensions(
            LoadedLevel::hackable_from_json(&bytes).unwrap(),
            assets,
            (
                dimensions[0].as_f64().unwrap() as f32 + 1.,
                dimensions[1].as_f64().unwrap() as f32 + 1.,
            ),
        )
    };
    let mut before_assets = LevelAssets::new();
    let before = load(&manifest.before, &mut before_assets);
    let mut after_assets = LevelAssets::new();
    let after = load(&manifest.after, &mut after_assets);
    let handle = |engine: &Engine, number: u16| {
        let index = engine.fast_grid().level.sector_number_map
            [&SectorNumber::new(i16::try_from(number).unwrap())];
        SectorHandle::new(number)
            .unwrap()
            .with_arena_index(SectorIndex::new(u32::try_from(index).unwrap()).unwrap())
    };
    let sample = |engine: &Engine, assets: &LevelAssets, sector, layer, point: MapPoint| {
        engine
            .get_projection_area_index(assets, sector, layer, point)
            .map(|index| {
                let obstacle = &assets.environment.static_sight_obstacles[usize::from(index)];
                (
                    obstacle.compute_top_z_from_projection(point.x, point.y),
                    assets
                        .environment
                        .material_sectors
                        .material_at_with_obstacle(Some(obstacle), point),
                )
            })
    };
    let mut report = ProjectionQueryReport {
        queries: 0,
        receiving: 0,
        height_differences: 0,
        material_differences: 0,
        coverage_differences: 0,
        maximum_height_difference: 0.,
        first_differences: vec![],
    };
    for case in manifest.cases {
        let a = handle(&before, case.before_sector);
        let b = handle(&after, case.after_sector);
        let [min_x, min_y, max_x, max_y] = case.bounds;
        assert!(min_x < max_x && min_y < max_y, "empty probe bounds");
        let mut receiving = 0;
        // Include integer boundaries and half-pixel interiors. This is a sampled
        // comparison, not proof about every continuous actor position.
        for y in min_y * 2..=max_y * 2 {
            for x in min_x * 2..=max_x * 2 {
                let point = MapPoint::new(x as f32 / 2., y as f32 / 2.);
                let old = sample(&before, &before_assets, a, case.layer, point);
                let new = sample(&after, &after_assets, b, case.layer, point);
                if old != new && report.first_differences.len() < 8 {
                    report.first_differences.push(format!(
                        "{point:?}, layer {}: {old:?} -> {new:?}",
                        case.layer
                    ));
                }
                match (old, new) {
                    (Some((old_height, old_material)), Some((new_height, new_material))) => {
                        report.height_differences += usize::from(old_height != new_height);
                        report.material_differences += usize::from(old_material != new_material);
                        report.maximum_height_difference = report
                            .maximum_height_difference
                            .max((old_height - new_height).abs());
                    }
                    (None, None) => {}
                    _ => report.coverage_differences += 1,
                }
                report.queries += 1;
                receiving += usize::from(old.is_some());
            }
        }
        assert!(receiving > 0, "probe never reached a projection surface");
        report.receiving += receiving;
    }
    let report_json = serde_json::to_string_pretty(&report).unwrap();
    std::fs::write(manifest_path.with_extension("report.json"), &report_json).unwrap();
    println!("{report_json}");
    assert_eq!(
        report.coverage_differences, 0,
        "projection coverage changed"
    );
    assert_eq!(
        report.material_differences, 0,
        "projection material changed"
    );
    assert_eq!(report.height_differences, 0, "projection elevation changed");
}

#[test]
#[ignore = "requires static diagnostic exports via ROBIN_ASSET_MAP_DIAGNOSTICS"]
fn recovered_static_exports_construct_native_geometry() {
    let directory = std::path::PathBuf::from(
        std::env::var("ROBIN_ASSET_MAP_DIAGNOSTICS").expect("diagnostic directory"),
    );
    let manifest: serde_json::Value =
        serde_json::from_slice(&std::fs::read(directory.join("diagnostics.json")).unwrap())
            .unwrap();
    assert_eq!(
        manifest["scope"],
        "static-geometry-only-not-gameplay-parity"
    );
    let mut count = 0;
    assert_ne!(manifest["complete"], false, "incomplete diagnostic batch");
    for result in manifest["results"].as_array().unwrap() {
        assert!(result["error"].is_null(), "failed diagnostic: {result}");
        let file = result["file"].as_str().expect("missing diagnostic file");
        let bytes = std::fs::read(directory.join(file)).unwrap();
        let descriptor: serde_json::Value = serde_json::from_slice(&bytes).unwrap();
        let geometry = &descriptor["asset_geometry"];
        let dims = &descriptor["walkable_polygon"][2];
        let level = LoadedLevel::hackable_from_json(&bytes).unwrap();
        let jump_pairs = level.proto.jump_line_pairs.clone();
        let jump_zones = level.proto.jump_zones.clone();
        let expected_masks = level.proto.masks.clone();
        let expected_sounds = level.proto.sound_sources.clone();
        let expected_ambience = level.mission.header.ambiance;
        let mut assets = LevelAssets::new();
        let engine = construct_with_dimensions(
            level,
            &mut assets,
            (
                dims[0].as_f64().unwrap() as f32 + 1.,
                dims[1].as_f64().unwrap() as f32 + 1.,
            ),
        );
        assert_eq!(
            assets.environment.static_sight_obstacles.len(),
            geometry["sight_obstacles"].as_array().unwrap().len(),
            "{file}"
        );
        let areas: usize = geometry["motion_data"]["layers"]
            .as_array()
            .unwrap()
            .iter()
            .map(|l| l.as_array().unwrap().len())
            .sum();
        assert_eq!(
            assets
                .navigation
                .pathfinder_graph
                .static_data
                .move_layers
                .iter()
                .map(Vec::len)
                .sum::<usize>(),
            areas,
            "{file}"
        );
        assert!(!engine.fast_grid().level.blocks.is_empty(), "{file}");
        let grid = engine.fast_grid();
        assert_eq!(
            assets.audio.sound_source_required_ids,
            expected_sounds
                .iter()
                .filter(|s| s.ambience_filter & expected_ambience != 0)
                .map(|s| u32::try_from(s.id).unwrap())
                .collect(),
            "{file}: required sound samples"
        );
        let snapshot = serde_json::to_value(engine.capture_persisted_state().unwrap()).unwrap();
        let sounds = snapshot["feedback"]["sound_sim"]["sources"]["sources"]
            .as_array()
            .unwrap();
        assert_eq!(
            sounds.len(),
            expected_sounds.len(),
            "{file}: sound source handles"
        );
        for (index, expected) in expected_sounds.iter().enumerate() {
            let actual = &sounds[index];
            if expected.ambience_filter & expected_ambience == 0 {
                assert!(actual.is_null(), "{file}: filtered sound {index}");
                continue;
            }
            let shape: Vec<_> = expected
                .polyline
                .as_deref()
                .unwrap_or_default()
                .iter()
                .map(|&(x, y)| robin_engine::coordinates::MapPoint::new(x as f32, y as f32))
                .collect();
            assert_eq!(
                actual["shape"],
                serde_json::to_value(shape).unwrap(),
                "{file}: sound {index} geometry"
            );
            let (min, max, step) = expected.delayed_params.unwrap_or((0, 0, 0));
            assert_eq!(
                actual["min_delay"], min,
                "{file}: sound {index} minimum delay"
            );
            assert_eq!(
                actual["max_delay"], max,
                "{file}: sound {index} maximum delay"
            );
            assert_eq!(
                actual["delay_stepping"],
                step + 1,
                "{file}: sound {index} stepping"
            );
        }
        assert_eq!(grid.level.masks.len(), expected_masks.len(), "{file}");
        for (index, (actual, expected)) in grid.level.masks.iter().zip(&expected_masks).enumerate()
        {
            assert_eq!(actual.mask_type, expected.mask_type, "{file}: mask {index}");
            assert_eq!(actual.layer, expected.layer, "{file}: mask {index}");
            assert_eq!(
                actual
                    .obstacle_indices
                    .iter()
                    .map(|i| i.get())
                    .collect::<Vec<_>>(),
                expected
                    .obstacle_indices
                    .iter()
                    .map(|&i| u32::from(i))
                    .collect::<Vec<_>>(),
                "{file}: mask {index} obstacle links"
            );
            assert_eq!(
                actual.bitmap,
                robin_engine::mask::decode_mask_bitmap(
                    &expected.mask_data,
                    expected.box_size.0 as u16,
                    expected.box_size.1 as u16,
                ),
                "{file}: mask {index}"
            );
            assert!(
                grid.level.layers[usize::from(actual.layer)]
                    .mask_indices
                    .iter()
                    .any(|&i| usize::from(i) == index),
                "{file}: unregistered mask {index}"
            );
        }
        assert_eq!(grid.level.jump_lines.len(), jump_pairs.len() * 2, "{file}");
        for (pair_index, pair) in jump_pairs.iter().enumerate() {
            for (side, (raw, opposite)) in [(&pair.line1, &pair.line2), (&pair.line2, &pair.line1)]
                .into_iter()
                .enumerate()
            {
                let index = pair_index * 2 + side;
                let line = &grid.level.jump_lines[index];
                assert_eq!(
                    line.associated_line_index,
                    Some((index ^ 1) as u32),
                    "{file}"
                );
                assert_eq!(line.long_jump_forced, pair.jump_long, "{file}");
                assert_eq!(
                    (line.point_a.x, line.point_a.y, line.z_a),
                    (
                        raw.point_a.0 as f32,
                        raw.point_a.1 as f32,
                        raw.point_a.2 as f32
                    ),
                    "{file}"
                );
                assert_eq!(
                    (line.point_b.x, line.point_b.y, line.z_b),
                    (
                        raw.point_b.0 as f32,
                        raw.point_b.1 as f32,
                        raw.point_b.2 as f32
                    ),
                    "{file}"
                );
                let zone = &jump_zones[opposite.jump_zone_index as usize];
                let home = &grid.level.sectors[line.sector_index.unwrap().get() as usize];
                assert_eq!(line.layer, zone.layer, "{file}");
                assert_eq!(home.layer, zone.layer, "{file}");
                assert!(
                    home.jump_line_indices
                        .iter()
                        .any(|id| id.get() as usize == index),
                    "{file}"
                );
                assert!(!home.gate_indices.is_empty(), "{file}");
            }
        }
        println!(
            "{file}: constructed {areas} areas, {} sight obstacles, {} doors, {} jump pairs",
            assets.environment.static_sight_obstacles.len(),
            engine.presentation_view().doors().len(),
            jump_pairs.len()
        );
        count += 1;
    }
    assert!(count > 0, "No successful static exports in manifest");
}

#[test]
fn door_endpoints_can_remain_outside_their_explicit_receiving_areas() {
    let mut assets = LevelAssets::new();
    let engine = construct(
        include_bytes!("fixtures/asset-door-anchor.level.json"),
        &mut assets,
    );
    let view = engine.presentation_view();
    let door = &view.doors()[0];
    assert_eq!((door.point_out.x, door.point_out.y), (395., 350.));
    assert_eq!((door.point_in.x, door.point_in.y), (405., 350.));
    assert_ne!(door.sector_out, door.sector_in);
    let grid = engine.fast_grid();
    let outside = &grid.level.sectors[door.sector_out_index.unwrap().get() as usize];
    let inside = &grid.level.sectors[door.sector_in_index.unwrap().get() as usize];
    assert!(!outside.contains_point(door.point_out));
    assert!(!inside.contains_point(door.point_in));
    assert!(outside.contains_point(robin_engine::coordinates::MapPoint::new(380., 350.)));
    assert!(inside.contains_point(robin_engine::coordinates::MapPoint::new(420., 350.)));
    assert!(!outside.gate_indices.is_empty());
    assert!(!inside.gate_indices.is_empty());
    assert_eq!(grid.level.door_projection_infos.len(), 1);
}

#[test]
fn nonrendering_asset_volume_constructs_navigation_and_sight() {
    let mut assets = LevelAssets::new();
    let engine = construct(
        include_bytes!("fixtures/asset-nonrendering-volume.level.json"),
        &mut assets,
    );
    let grid = engine.fast_grid();
    assert_eq!(assets.environment.static_sight_obstacles.len(), 1);
    assert_eq!(grid.level.door_projection_infos.len(), 1);
    use robin_engine::coordinates::MapPoint;
    assert!(grid.is_reachable_thin(MapPoint::new(310., 320.), MapPoint::new(370., 320.), 0));
    assert!(!grid.is_reachable_thin(MapPoint::new(330., 345.), MapPoint::new(360., 345.), 0));
}

#[test]
fn ordinary_region_crosses_projection_planes_without_a_gate() {
    let mut assets = LevelAssets::new();
    let engine = construct(
        include_bytes!("fixtures/asset-multi-plane-region.level.json"),
        &mut assets,
    );
    let grid = engine.fast_grid();
    assert!(grid.level.door_projection_infos.is_empty());
    assert!(engine.presentation_view().doors().is_empty());
    assert!(grid.level.sectors.iter().all(|s| !s.sector_type.is_lift()));
    let planes = &assets.environment.static_sight_obstacles;
    assert_eq!(planes.len(), 2);
    assert!((planes[1].compute_top_z_from_projection(395., 330.) - 20.).abs() < 0.001);
    assert!((planes[0].compute_top_z_from_projection(405., 280.) - 70.).abs() < 0.001);
    use robin_engine::coordinates::MapPoint;
    let layer = grid.level.sectors[0].layer;
    assert!(grid.is_reachable_thin(MapPoint::new(395., 330.), MapPoint::new(405., 280.), layer));
}

#[test]
fn compound_lift_keeps_one_native_sector_and_each_projection_plane() {
    let mut assets = LevelAssets::new();
    let engine = construct(
        include_bytes!("fixtures/asset-compound-lift.level.json"),
        &mut assets,
    );
    let grid = engine.fast_grid();
    let lifts: Vec<_> = grid
        .level
        .sectors
        .iter()
        .filter(|s| s.sector_type.is_lift())
        .collect();
    assert_eq!(lifts.len(), 1);
    assert_eq!(lifts[0].gate_indices.len(), 2);
    assert_eq!(grid.level.door_projection_infos.len(), 2);
    let planes = &assets.environment.static_sight_obstacles;
    let low = &planes[planes.len() - 2];
    let high = &planes[planes.len() - 1];
    assert!((low.compute_top_z_from_projection(395., 330.) - 20.).abs() < 0.001);
    assert!((high.compute_top_z_from_projection(405., 280.) - 70.).abs() < 0.001);
    let view = engine.presentation_view();
    assert_eq!(view.doors()[0].sector_in, view.doors()[1].sector_in);
    use robin_engine::coordinates::MapPoint;
    let layer = grid
        .level
        .sectors
        .iter()
        .find(|s| s.sector_type.is_lift())
        .unwrap()
        .layer;
    assert!(grid.is_reachable_thin(MapPoint::new(395., 330.), MapPoint::new(405., 280.), layer));
}

#[test]
fn touching_navigation_regions_keep_native_boundaries_and_gate_links() {
    let mut assets = LevelAssets::new();
    let engine = construct(
        include_bytes!("fixtures/asset-navigation-region.level.json"),
        &mut assets,
    );
    let grid = engine.fast_grid();
    assert_eq!(
        assets.navigation.pathfinder_graph.static_data.move_layers[0].len(),
        2
    );
    let view = engine.presentation_view();
    let door = &view.doors()[0];
    assert_ne!(door.sector_in, door.sector_out);
    use robin_engine::coordinates::MapPoint;
    assert!(grid.is_reachable_thin(MapPoint::new(310., 320.), MapPoint::new(390., 320.), 0));
    assert!(!grid.is_reachable_thin(MapPoint::new(390., 320.), MapPoint::new(410., 320.), 0));
    assert_eq!(
        grid.level
            .sectors
            .iter()
            .filter(|s| !s.gate_indices.is_empty())
            .count(),
        2
    );
}

#[test]
fn compiled_jump_pairs_construct_native_zones_heights_helpers_and_gates() {
    let mut assets = LevelAssets::new();
    let engine = construct(
        include_bytes!("fixtures/asset-jump.level.json"),
        &mut assets,
    );
    let grid = engine.fast_grid();
    let lines = &grid.level.jump_lines;
    assert_eq!(lines.len(), 2);
    assert_eq!((lines[0].layer, lines[1].layer), (0, 1));
    assert_eq!((lines[0].z_a, lines[1].z_a), (0., 100.));
    assert_eq!(lines[0].associated_line_index, Some(1));
    assert_eq!(lines[1].associated_line_index, Some(0));
    assert!(lines.iter().all(|line| line.long_jump_forced));
    assert!(!lines[0].helper_needed);
    assert!(lines[1].helper_needed);
    let zones: Vec<_> = grid
        .level
        .sectors
        .iter()
        .filter(|s| {
            s.sector_type
                .contains(robin_engine::sector::SectorType::JUMP)
        })
        .collect();
    assert_eq!(zones.len(), 2);
    for (index, line) in lines.iter().enumerate() {
        let home = line.sector_index.unwrap();
        let sector = &grid.level.sectors[home.get() as usize];
        assert_eq!(sector.layer, index as u16);
        assert_eq!(sector.jump_line_indices.len(), 1);
        assert!(!sector.gate_indices.is_empty());
        assert!(
            zones
                .iter()
                .any(|zone| zone.layer == line.layer && zone.underlying_sector == Some(home))
        );
    }
}

#[test]
fn detached_jump_assets_preserve_complete_pair_registrations() {
    let mut assets = LevelAssets::new();
    let engine = construct(
        include_bytes!("fixtures/asset-jump-detached.level.json"),
        &mut assets,
    );
    let grid = engine.fast_grid();
    let lines = &grid.level.jump_lines;
    assert_eq!(lines.len(), 2);
    assert_eq!(lines[0].associated_line_index, Some(1));
    assert_eq!(lines[1].associated_line_index, Some(0));
    assert_eq!((lines[0].z_a, lines[1].z_a), (0., 100.));
    assert!(lines.iter().all(|line| line.long_jump_forced));
    let zones: Vec<_> = grid
        .level
        .sectors
        .iter()
        .filter(|sector| {
            sector
                .sector_type
                .contains(robin_engine::sector::SectorType::JUMP)
        })
        .collect();
    assert_eq!(zones.len(), 2);
    for line in lines {
        let home = line.sector_index.unwrap();
        assert!(
            zones
                .iter()
                .any(|zone| zone.underlying_sector == Some(home))
        );
        let sector = &grid.level.sectors[home.get() as usize];
        assert_eq!(sector.jump_line_indices.len(), 1);
        assert!(!sector.gate_indices.is_empty());
    }
}

#[test]
fn compiled_jump_metadata_rejects_orphan_zones_and_stale_links() {
    let value: serde_json::Value =
        serde_json::from_slice(include_bytes!("fixtures/asset-jump.level.json")).unwrap();
    for (field, replacement) in [
        ("jump_line_pairs", serde_json::json!([])),
        ("jump_zones", serde_json::json!([])),
    ] {
        let mut bad = value.clone();
        bad["asset_geometry"][field] = replacement;
        assert!(
            LoadedLevel::hackable_from_json(&serde_json::to_vec(&bad).unwrap())
                .unwrap_err()
                .contains("jump")
        );
    }
    let mut bad = value;
    bad["asset_geometry"]["jump_zones"][0]["sector"] = 123.into();
    assert!(
        LoadedLevel::hackable_from_json(&serde_json::to_vec(&bad).unwrap())
            .unwrap_err()
            .contains("jump zone")
    );
}

#[test]
fn compiled_light_regions_follow_mission_ambience_without_changing_interior_links() {
    use robin_engine::coordinates::MapPoint;
    for mask in [1, 2] {
        let mut loaded =
            LoadedLevel::hackable_from_json(include_bytes!("fixtures/asset-light.level.json"))
                .unwrap();
        loaded.mission.header.ambiance = mask;
        let mut assets = LevelAssets::new();
        let engine = construct_loaded(loaded, &mut assets);
        let grid = engine.fast_grid();
        assert_eq!(
            grid.is_in_shadow_sector(MapPoint::new(320., 320.), 0),
            mask == 1
        );
        assert_eq!(
            grid.is_in_shadow_sector(MapPoint::new(370., 320.), 0),
            mask == 2
        );
        assert!(!grid.is_in_shadow_sector(MapPoint::new(320., 350.), 0));
        assert_eq!(grid.level.door_projection_infos.len(), 3);
    }
}

#[test]
#[ignore = "requires ROBIN_ASSET_MAP_DIAGNOSTICS"]
fn recovered_light_exports_preserve_contours_layers_and_ambience() {
    use robin_engine::coordinates::MapPoint;
    use robin_engine::sector::SectorType;
    let directory = std::path::PathBuf::from(std::env::var("ROBIN_ASSET_MAP_DIAGNOSTICS").unwrap());
    let manifest: serde_json::Value =
        serde_json::from_slice(&std::fs::read(directory.join("diagnostics.json")).unwrap())
            .unwrap();
    assert_eq!(manifest["complete"], true);
    for result in manifest["results"].as_array().unwrap() {
        let file = result["file"].as_str().unwrap();
        let bytes = std::fs::read(directory.join(file)).unwrap();
        let descriptor: serde_json::Value = serde_json::from_slice(&bytes).unwrap();
        let dimensions = &descriptor["walkable_polygon"][2];
        for ambience in [1, 2, 4] {
            let mut level = LoadedLevel::hackable_from_json(&bytes).unwrap();
            level.mission.header.ambiance = ambience;
            let lights = level.proto.light_sectors.clone();
            let mut assets = LevelAssets::new();
            let engine = construct_with_dimensions(
                level,
                &mut assets,
                (
                    dimensions[0].as_f64().unwrap() as f32 + 1.,
                    dimensions[1].as_f64().unwrap() as f32 + 1.,
                ),
            );
            let grid = engine.fast_grid();
            for light in &lights {
                let points: Vec<_> = light
                    .polygon
                    .points
                    .iter()
                    .map(|&(x, y)| MapPoint::new(x as f32, y as f32))
                    .collect();
                let expected = lights.iter().any(|other| {
                    other.layer == light.layer
                        && other.polygon.points == light.polygon.points
                        && other.ambience & ambience != 0
                });
                let active = grid
                    .level
                    .sectors
                    .iter()
                    .enumerate()
                    .any(|(index, sector)| {
                        sector.sector_type.contains(SectorType::SHADOW)
                            && sector.layer == light.layer
                            && sector.points == points
                            && grid.is_sector_active(index as u32)
                    });
                assert_eq!(
                    active, expected,
                    "{file}: light layer {} ambience {ambience}",
                    light.layer
                );
            }
            eprintln!(
                "{file}: checked {} light contours for ambience {ambience}",
                lights.len()
            );
        }
    }
}

#[test]
fn compiled_traversal_light_uses_the_lift_layer_and_mission_ambience() {
    use robin_engine::coordinates::MapPoint;
    for mask in [1, 2] {
        let mut loaded =
            LoadedLevel::hackable_from_json(include_bytes!("fixtures/asset-lift-light.level.json"))
                .unwrap();
        loaded.mission.header.ambiance = mask;
        let mut assets = LevelAssets::new();
        let engine = construct_loaded(loaded, &mut assets);
        let grid = engine.fast_grid();
        let layer = grid
            .level
            .sectors
            .iter()
            .find(|sector| sector.sector_type.is_lift())
            .unwrap()
            .layer;
        assert_eq!(
            grid.is_in_shadow_sector(MapPoint::new(400., 300.), layer),
            mask == 2
        );
        assert!(!grid.is_in_shadow_sector(MapPoint::new(400., 300.), 0));
        assert!(!grid.is_in_shadow_sector(MapPoint::new(450., 300.), layer));
        assert_eq!(grid.level.door_projection_infos.len(), 2);
    }
}

#[test]
fn compiled_light_regions_reject_missing_layers_and_degenerate_contours() {
    let mut value: serde_json::Value =
        serde_json::from_slice(include_bytes!("fixtures/asset-light.level.json")).unwrap();
    value["asset_geometry"]["light_sectors"][0]["layer"] = 123.into();
    assert!(
        LoadedLevel::hackable_from_json(&serde_json::to_vec(&value).unwrap())
            .unwrap_err()
            .contains("light geometry")
    );
    value["asset_geometry"]["light_sectors"][0]["layer"] = 0.into();
    value["asset_geometry"]["light_sectors"][0]["polygon"]["points"] =
        serde_json::json!([[1, 2], [3, 4]]);
    assert!(
        LoadedLevel::hackable_from_json(&serde_json::to_vec(&value).unwrap())
            .unwrap_err()
            .contains("light geometry")
    );
}

#[test]
fn sight_transitions_reject_missing_duplicate_and_projection_obstacles() {
    let source: serde_json::Value =
        serde_json::from_slice(include_bytes!("fixtures/asset-sight-transition.level.json"))
            .unwrap();
    for index in [999, 0] {
        let mut bad = source.clone();
        bad["asset_geometry"]["movement_transitions"][0]["applied_sight"] =
            serde_json::json!([index]);
        assert!(LoadedLevel::hackable_from_json(&serde_json::to_vec(&bad).unwrap()).is_err());
    }
    let mut bad = source;
    bad["asset_geometry"]["sight_obstacles"][0]["projection_area"] = serde_json::json!([0, 0]);
    assert!(LoadedLevel::hackable_from_json(&serde_json::to_vec(&bad).unwrap()).is_err());
}

#[test]
fn compiled_door_links_reject_missing_duplicate_and_conflicting_bindings() {
    let source: serde_json::Value =
        serde_json::from_slice(include_bytes!("fixtures/asset-door-transition.level.json"))
            .unwrap();
    let loaded = LoadedLevel::hackable_from_json(&serde_json::to_vec(&source).unwrap()).unwrap();
    assert!(loaded.proto.patches[0].door_triggered);
    assert!(!loaded.proto.patches[0].triggers_door);
    assert_eq!(loaded.proto.patches[0].door_indices, vec![2]);
    assert!(!loaded.proto.patches[1].door_triggered);
    assert!(loaded.proto.patches[1].triggers_door);
    assert_eq!(loaded.proto.patches[1].door_indices, vec![0, 1]);
    for indices in [vec![], vec![3], vec![0, 0]] {
        let mut bad = source.clone();
        bad["asset_geometry"]["movement_transitions"][1]["door_links"]["indices"] =
            serde_json::json!(indices);
        assert!(
            LoadedLevel::hackable_from_json(&serde_json::to_vec(&bad).unwrap())
                .unwrap_err()
                .contains("transition door binding")
        );
    }
    let mut bad = source;
    bad["asset_geometry"]["movement_transitions"][1]["door_links"] =
        serde_json::json!({"mode":"trigger-transition","indices":[2]});
    assert!(
        LoadedLevel::hackable_from_json(&serde_json::to_vec(&bad).unwrap())
            .unwrap_err()
            .contains("transition door binding")
    );
}

#[test]
fn compiled_movement_transitions_reject_stale_or_unbound_state_bits() {
    let value: serde_json::Value = serde_json::from_slice(include_bytes!(
        "fixtures/asset-movement-transition.level.json"
    ))
    .unwrap();
    let mut bad = value.clone();
    bad["asset_geometry"]["movement_transitions"][0]["motion_changes"][0]["sector"] = 123.into();
    assert!(
        LoadedLevel::hackable_from_json(&serde_json::to_vec(&bad).unwrap())
            .unwrap_err()
            .contains("missing area")
    );
    let mut bad = value.clone();
    bad["asset_geometry"]["movement_transitions"][0]["motion_changes"][0]["changing_obstacle"] =
        16.into();
    assert!(
        LoadedLevel::hackable_from_json(&serde_json::to_vec(&bad).unwrap())
            .unwrap_err()
            .contains("bit pair")
    );
    let mut bad = value.clone();
    bad["asset_geometry"]["movement_transitions"] = serde_json::json!([]);
    assert!(
        LoadedLevel::hackable_from_json(&serde_json::to_vec(&bad).unwrap())
            .unwrap_err()
            .contains("no independent transition")
    );
    let mut bad = value;
    let duplicate = bad["asset_geometry"]["movement_transitions"][0]["motion_changes"][0].clone();
    bad["asset_geometry"]["movement_transitions"][0]["motion_changes"]
        .as_array_mut()
        .unwrap()
        .push(duplicate);
    assert!(
        LoadedLevel::hackable_from_json(&serde_json::to_vec(&bad).unwrap())
            .unwrap_err()
            .contains("duplicate")
    );
}

#[test]
fn environmental_sounds_load_from_compiled_assets_and_filter_unused_samples() {
    let bytes = include_bytes!("fixtures/asset-sound.level.json");
    let level = LoadedLevel::hackable_from_json(bytes).unwrap();
    let source = &level.proto.sound_sources[0];
    assert_eq!(
        source.polyline.as_deref(),
        Some([(310, 315), (330, 335)].as_slice())
    );
    assert_eq!(source.delayed_params, Some((100, 200, 4)));
    assert_eq!(source.altitude, 1);
    assert_eq!(source.noise_covering_distance, Some(60));
    let mut assets = LevelAssets::new();
    let engine = construct(bytes, &mut assets);
    assert_eq!(
        assets.audio.sound_source_required_ids,
        [17].into_iter().collect()
    );
    let snapshot = serde_json::to_value(engine.capture_persisted_state().unwrap()).unwrap();
    let sources = &snapshot["feedback"]["sound_sim"]["sources"]["sources"];
    assert_eq!(sources[0]["delay_stepping"], 5);
    assert_eq!(sources[0]["inner_volume"], 178);
    assert_eq!(sources[0]["noise_covering_distance"], 60);
    assert!(sources[1].is_null());
}

#[test]
fn environmental_sounds_reject_incomplete_geometry_and_overflowing_delay() {
    let mut value: serde_json::Value =
        serde_json::from_slice(include_bytes!("fixtures/asset-sound.level.json")).unwrap();
    value["asset_geometry"]["sound_sources"][0]["delayed_params"] =
        serde_json::json!([0, 1, 65535]);
    assert!(
        LoadedLevel::hackable_from_json(&serde_json::to_vec(&value).unwrap())
            .unwrap_err()
            .contains("sound source")
    );
    value["asset_geometry"]["sound_sources"][0]["delayed_params"] = serde_json::json!([0, 1, 0]);
    value["asset_geometry"]["sound_sources"][0]["inner_volume"] = serde_json::Value::Null;
    assert!(LoadedLevel::hackable_from_json(&serde_json::to_vec(&value).unwrap()).is_err());
}

#[test]
fn materials_keep_ground_and_obstacle_queries_separate() {
    use robin_engine::{coordinates::MapPoint, element::GameMaterial};
    let mut assets = LevelAssets::new();
    let _engine = construct(
        include_bytes!("fixtures/asset-material.level.json"),
        &mut assets,
    );
    let materials = &assets.environment.material_sectors;
    assert_eq!(
        materials.material_at_layer(MapPoint::new(320., 320.), 0),
        GameMaterial::Stone
    );
    assert_eq!(
        materials.material_at_layer(MapPoint::new(320., 320.), 1),
        GameMaterial::Ground
    );
    assert_eq!(
        materials.material_at(MapPoint::new(345., 345.)),
        GameMaterial::Ground
    );
    let obstacle = assets
        .environment
        .static_sight_obstacles
        .iter()
        .find(|obstacle| !obstacle.material_sectors.is_empty())
        .unwrap();
    assert_eq!(
        materials.material_at_with_obstacle(Some(obstacle), MapPoint::new(345., 345.)),
        GameMaterial::Water
    );
    assert!(assets.environment.water_zones.zones.is_empty());
}

#[test]
fn receiving_materials_keep_navigation_connected_and_ground_independent() {
    use robin_engine::{coordinates::MapPoint, element::GameMaterial};
    let mut assets = LevelAssets::new();
    let engine = construct(
        include_bytes!("fixtures/asset-projection-material.level.json"),
        &mut assets,
    );
    let receivers = &assets.environment.static_sight_obstacles;
    assert_eq!(receivers.len(), 2);
    assert_eq!(
        receivers[0].projection_area_ref(),
        receivers[1].projection_area_ref()
    );
    let materials = &assets.environment.material_sectors;
    for (point, expected) in [
        (MapPoint::new(320., 300.), GameMaterial::Water),
        (MapPoint::new(350., 330.), GameMaterial::Stone),
        (MapPoint::new(450., 330.), GameMaterial::Leaves),
    ] {
        let receiver = receivers
            .iter()
            .find(|obstacle| obstacle.contains_point_projection(point))
            .unwrap();
        assert_eq!(
            materials.material_at_with_obstacle(Some(receiver), point),
            expected
        );
        assert!((receiver.compute_top_z_from_projection(point.x, point.y) - 20.).abs() < 0.001);
        assert_eq!(materials.material_at_layer(point, 0), GameMaterial::Ground);
    }
    let grid = engine.fast_grid();
    assert!(grid.is_reachable_thin(MapPoint::new(350., 330.), MapPoint::new(450., 330.), 1));
}

#[test]
fn empty_ground_material_list_does_not_activate_obstacle_materials() {
    use robin_engine::{coordinates::MapPoint, element::GameMaterial};
    let mut value: serde_json::Value =
        serde_json::from_slice(include_bytes!("fixtures/asset-material.level.json")).unwrap();
    value["asset_geometry"]["sight_material_indices"] = serde_json::json!([]);
    let mut assets = LevelAssets::new();
    let _engine = construct(&serde_json::to_vec(&value).unwrap(), &mut assets);
    assert!(assets.environment.material_sectors.sectors.is_empty());
    assert!(assets.environment.water_zones.zones.is_empty());
    assert_eq!(
        assets
            .environment
            .material_sectors
            .material_at(MapPoint::new(345., 345.)),
        GameMaterial::Ground
    );
}

#[test]
fn invalid_material_references_are_rejected() {
    let mut value: serde_json::Value =
        serde_json::from_slice(include_bytes!("fixtures/asset-material.level.json")).unwrap();
    value["asset_geometry"]["sight_material_indices"] = serde_json::json!([99]);
    assert!(
        LoadedLevel::hackable_from_json(&serde_json::to_vec(&value).unwrap())
            .unwrap_err()
            .contains("material")
    );
    value["asset_geometry"]["sight_material_indices"] = serde_json::json!([]);
    value["asset_geometry"]["sight_obstacles"][0]["material_indices"] = serde_json::json!([99]);
    assert!(LoadedLevel::hackable_from_json(&serde_json::to_vec(&value).unwrap()).is_err());
}

#[test]
fn terrain_defaults_reach_material_fallback_and_map_metadata() {
    use robin_engine::{coordinates::MapPoint, element::GameMaterial};
    let mut value: serde_json::Value =
        serde_json::from_slice(include_bytes!("fixtures/asset-material.level.json")).unwrap();
    value["asset_geometry"]["map_settings"] =
        serde_json::json!({"forest_level":true,"default_material":4});
    value["asset_geometry"]["material_sectors"][1]["material"] = 9.into();
    let bytes = serde_json::to_vec(&value).unwrap();
    let loaded = LoadedLevel::hackable_from_json(&bytes).unwrap();
    let misc = loaded.proto.misc.unwrap();
    assert!(misc.forest_level);
    assert_eq!(misc.default_material, 4);
    let mut assets = LevelAssets::new();
    let engine = construct(&bytes, &mut assets);
    assert!(engine.weather().is_forest_level);
    let materials = &assets.environment.material_sectors;
    assert_eq!(
        materials.material_at_layer(MapPoint::new(320., 320.), 0),
        GameMaterial::Leaves
    );
    assert_eq!(
        materials.material_at(MapPoint::new(100., 100.)),
        GameMaterial::Leaves
    );
    value["asset_geometry"]["map_settings"]["default_material"] = 9.into();
    assert!(
        LoadedLevel::hackable_from_json(&serde_json::to_vec(&value).unwrap())
            .unwrap_err()
            .contains("default material")
    );
}

#[test]
fn map_geometry_does_not_accept_embedded_player_spawns() {
    let mut value: serde_json::Value =
        serde_json::from_slice(include_bytes!("fixtures/asset-compiled.level.json")).unwrap();
    value["spawn_player"] = true.into();
    value["spawn"] = serde_json::json!([320, 320]);
    let error = LoadedLevel::hackable_from_json(&serde_json::to_vec(&value).unwrap()).unwrap_err();
    assert!(error.contains("use a mission"), "{error}");
}

#[test]
fn geometry_warnings_do_not_require_mission_content() {
    let mut value: serde_json::Value =
        serde_json::from_slice(include_bytes!("fixtures/asset-compiled.level.json")).unwrap();
    value["asset_geometry"]["warnings"] = serde_json::json!(["Generated fragment omitted"]);
    let level = LoadedLevel::hackable_from_json(&serde_json::to_vec(&value).unwrap()).unwrap();
    assert!(level.mission.beam_mes.is_empty());
}

fn construct(bytes: &[u8], assets: &mut LevelAssets) -> Engine {
    let level = LoadedLevel::hackable_from_json(bytes).unwrap();
    construct_loaded(level, assets)
}

fn construct_loaded(level: LoadedLevel, assets: &mut LevelAssets) -> Engine {
    construct_with_dimensions(level, assets, (2000., 2000.))
}

fn construct_with_dimensions(
    level: LoadedLevel,
    assets: &mut LevelAssets,
    dimensions: (f32, f32),
) -> Engine {
    assert!(level.mission.beam_mes.is_empty());
    assert!(level.mission.soldiers.is_empty());
    let mut profiles = robin_engine::profiles::ProfileManager::new();
    let mut campaign = robin_engine::campaign::Campaign::new();
    let index = campaign
        .force_next_mission_by_name(&mut profiles, "asset-test", "asset-test", true)
        .unwrap();
    campaign.current_mission_idx = Some(index);
    assets.profile_manager = std::sync::Arc::new(profiles);
    let engine = Engine::new(EngineArgs {
        campaign,
        level: LevelLoadArgs {
            assets,
            level_directory: "",
            progress: &mut |_| {},
            loaded: level,
            bg_pixel_dims: dimensions,
        },
        ground_mark_sprite: None,
        titbit_row_frame_counts: vec![],
        rng_seed: 0,
        original_rng_replay: None,
        sim_config: SimConfig {
            script_enabled: false,
            ..Default::default()
        },
    })
    .expect("construct compiled asset map without game files");
    engine
}

#[test]
fn asset_compiler_output_constructs_live_navigation_sight_and_door_links() {
    let mut assets = LevelAssets::new();
    let engine = construct(
        include_bytes!("fixtures/asset-compiled.level.json"),
        &mut assets,
    );
    let grid = engine.fast_grid();
    assert!(!grid.level.blocks.is_empty());
    assert_eq!(grid.level.door_projection_infos.len(), 1);
    assert!(!assets.environment.static_sight_obstacles.is_empty());
    assert!(
        grid.level
            .sectors
            .iter()
            .filter(|sector| !sector.gate_indices.is_empty())
            .count()
            >= 2
    );
    assert_eq!(
        assets.navigation.pathfinder_graph.static_data.move_layers[0].len(),
        2
    );
    use robin_engine::coordinates::MapPoint;
    assert!(grid.is_reachable_thin(MapPoint::new(310., 320.), MapPoint::new(370., 320.), 0));
    assert!(!grid.is_reachable_thin(MapPoint::new(330., 345.), MapPoint::new(360., 345.), 0));
}

#[test]
fn movement_clearance_opens_navigation_without_removing_sight_geometry() {
    let mut assets = LevelAssets::new();
    let engine = construct(
        include_bytes!("fixtures/asset-clearance.level.json"),
        &mut assets,
    );
    use robin_engine::coordinates::MapPoint;
    let grid = engine.fast_grid();
    assert!(grid.is_reachable_thin(MapPoint::new(330., 345.), MapPoint::new(360., 345.), 0));
    assert!(!grid.is_reachable_thin(MapPoint::new(330., 341.), MapPoint::new(360., 341.), 0));
    assert!(!assets.environment.static_sight_obstacles.is_empty());
}

#[test]
fn compiler_interchange_rejects_unresolved_asset_references() {
    let mut descriptor: serde_json::Value =
        serde_json::from_slice(include_bytes!("fixtures/asset-compiled.level.json")).unwrap();
    descriptor["asset_geometry"]["doors"][0]["sector_in"] = 65535.into();
    assert!(
        LoadedLevel::hackable_from_json(&serde_json::to_vec(&descriptor).unwrap())
            .unwrap_err()
            .contains("asset door")
    );
}

#[test]
fn non_clickable_passage_still_registers_navigation_links() {
    let mut descriptor: serde_json::Value =
        serde_json::from_slice(include_bytes!("fixtures/asset-compiled.level.json")).unwrap();
    descriptor["asset_geometry"]["doors"][0]["door_sector"]["points"] = serde_json::json!([]);
    let mut assets = LevelAssets::new();
    let engine = construct(&serde_json::to_vec(&descriptor).unwrap(), &mut assets);
    let grid = engine.fast_grid();
    assert_eq!(grid.level.door_projection_infos.len(), 1);
    assert_eq!(
        grid.level
            .sectors
            .iter()
            .filter(|s| !s.gate_indices.is_empty())
            .count(),
        2
    );
}

#[test]
fn compiled_door_retains_alternate_lock_rules() {
    let mut descriptor: serde_json::Value =
        serde_json::from_slice(include_bytes!("fixtures/asset-compiled.level.json")).unwrap();
    let door = &mut descriptor["asset_geometry"]["doors"][0];
    door["door_type"] = 7.into();
    door["locked_pc_after_patch"] = true.into();
    door["unlockable_after_patch"] = true.into();
    door["locked_npc_villain_after_patch"] = true.into();
    door["locked_npc_civilian_after_patch"] = true.into();
    let mut assets = LevelAssets::new();
    let engine = construct(&serde_json::to_vec(&descriptor).unwrap(), &mut assets);
    let mut door = engine.presentation_view().doors()[0].clone();
    assert_eq!(door.door_type, robin_engine::gate::DoorType::Trap);
    assert!(!door.locked_pc);
    door.swap_rights_patch();
    assert!(
        door.locked_pc && door.unlockable && door.locked_npc_villain && door.locked_npc_civilian
    );
    door.swap_rights_patch();
    assert!(
        !door.locked_pc
            && !door.unlockable
            && !door.locked_npc_villain
            && !door.locked_npc_civilian
    );
}

#[test]
fn sloped_asset_surface_constructs_elevation_and_navigation_holes() {
    let mut assets = LevelAssets::new();
    let engine = construct(
        include_bytes!("fixtures/asset-sloped.level.json"),
        &mut assets,
    );
    let surface = assets.environment.static_sight_obstacles.last().unwrap();
    assert!((surface.compute_top_z(320., 320.) - 10.).abs() < 0.001);
    assert!((surface.compute_top_z_from_projection(320., 310.) - 10.).abs() < 0.001);
    assert!((surface.compute_top_z_from_projection(400., 300.) - 50.).abs() < 0.001);
    use robin_engine::coordinates::MapPoint;
    let grid = engine.fast_grid();
    assert!(grid.is_reachable_thin(MapPoint::new(310., 315.), MapPoint::new(350., 295.), 0));
    // Cross the authored hole, away from the solid obstacle.
    assert!(!grid.is_reachable_thin(MapPoint::new(365., 337.5), MapPoint::new(385., 327.5), 0));
    // Cross the collision volume where it intersects the ramp.
    assert!(!grid.is_reachable_thin(MapPoint::new(330., 330.), MapPoint::new(360., 315.), 0));
}

#[test]
fn compiled_lift_registers_traversal_sector_and_both_door_links() {
    let mut assets = LevelAssets::new();
    let engine = construct(
        include_bytes!("fixtures/asset-lift.level.json"),
        &mut assets,
    );
    let grid = engine.fast_grid();
    let lift = grid
        .level
        .sectors
        .iter()
        .find(|s| s.sector_type.is_lift())
        .unwrap();
    assert_eq!(lift.lift_type, Some(robin_engine::sector::LiftType::Stairs));
    assert_eq!(lift.lift_direction, 4);
    assert_eq!(lift.gate_indices.len(), 2);
    assert_eq!(grid.level.door_projection_infos.len(), 2);
    assert_eq!(
        assets
            .navigation
            .pathfinder_graph
            .static_data
            .move_layers
            .len(),
        3
    );
}

#[test]
fn compiled_lift_rejects_dangling_and_incomplete_definitions() {
    let original: serde_json::Value =
        serde_json::from_slice(include_bytes!("fixtures/asset-lift.level.json")).unwrap();
    for field in ["motion_area_index", "lift_type", "direction"] {
        let mut bad = original.clone();
        bad["asset_geometry"]["lifts"][0][field] = 99.into();
        assert!(LoadedLevel::hackable_from_json(&serde_json::to_vec(&bad).unwrap()).is_err());
    }
    let mut missing = original;
    let mut flat = missing.clone();
    flat["asset_geometry"]["lifts"][0]["doors"][1]["point_out"][1] =
        flat["asset_geometry"]["lifts"][0]["doors"][0]["point_out"][1].clone();
    assert!(LoadedLevel::hackable_from_json(&serde_json::to_vec(&flat).unwrap()).is_err());
    missing["asset_geometry"]["lifts"] = serde_json::json!([]);
    assert!(
        LoadedLevel::hackable_from_json(&serde_json::to_vec(&missing).unwrap())
            .unwrap_err()
            .contains("no traversal definition")
    );
}

#[test]
fn lift_endpoints_are_selected_spatially_when_both_doors_use_low_actions() {
    let mut descriptor: serde_json::Value =
        serde_json::from_slice(include_bytes!("fixtures/asset-lift.level.json")).unwrap();
    descriptor["asset_geometry"]["lifts"][0]["doors"][1]["door_type"] = 5.into();
    let mut assets = LevelAssets::new();
    let engine = construct(&serde_json::to_vec(&descriptor).unwrap(), &mut assets);
    let view = engine.presentation_view();
    let doors = view.doors();
    let endpoints =
        robin_engine::gate::lift_endpoint_door_indices(doors, doors[0].sector_in).unwrap();
    assert_ne!(endpoints.0, endpoints.1);
    assert!(doors[endpoints.0 as usize].point_out.y > doors[endpoints.1 as usize].point_out.y);
}

#[test]
fn compiled_interior_registers_a_shared_building_sector() {
    let mut assets = LevelAssets::new();
    let engine = construct(
        include_bytes!("fixtures/asset-interior.level.json"),
        &mut assets,
    );
    let grid = engine.fast_grid();
    let buildings: Vec<_> = grid
        .level
        .sectors
        .iter()
        .filter(|s| s.sector_type.is_building())
        .collect();
    assert_eq!(buildings.len(), 1);
    assert_eq!(i16::from(buildings[0].sector_number), 4);
    assert_eq!(buildings[0].gate_indices.len(), 2);
    assert_eq!(grid.level.door_projection_infos.len(), 3);
}

#[test]
fn compiled_interior_connections_follow_independent_asset_placement() {
    for (bytes, expected_rooms, expected_entrances) in [
        (
            include_bytes!("fixtures/asset-interior-joined.level.json").as_slice(),
            1,
            2,
        ),
        (
            include_bytes!("fixtures/asset-interior-separated.level.json").as_slice(),
            2,
            1,
        ),
    ] {
        let mut assets = LevelAssets::new();
        let engine = construct(bytes, &mut assets);
        let grid = engine.fast_grid();
        let buildings: Vec<_> = grid
            .level
            .sectors
            .iter()
            .filter(|sector| sector.sector_type.is_building())
            .collect();
        assert_eq!(buildings.len(), expected_rooms);
        for building in buildings {
            assert_eq!(building.gate_indices.len(), expected_entrances);
        }
        assert_eq!(grid.level.door_projection_infos.len(), 2);
    }
}

#[test]
fn compiled_interior_rejects_invalid_entrance_identity() {
    let mut bad: serde_json::Value =
        serde_json::from_slice(include_bytes!("fixtures/asset-interior.level.json")).unwrap();
    bad["asset_geometry"]["buildings"][0]["Building"]["doors"][0]["sector_in"] = 65535.into();
    assert!(
        LoadedLevel::hackable_from_json(&serde_json::to_vec(&bad).unwrap())
            .unwrap_err()
            .contains("interior entrance")
    );
}

#[test]
fn materials_shift_interior_constructors_without_breaking_entrances() {
    let mut value: serde_json::Value =
        serde_json::from_slice(include_bytes!("fixtures/asset-interior.level.json")).unwrap();
    value["asset_geometry"]["material_sectors"] = serde_json::json!([
        {"material":2,"polygon":{"points":[[310,310],[320,310],[320,320],[310,320]]}}
    ]);
    value["asset_geometry"]["sight_material_indices"] = serde_json::json!([0]);
    for door in value["asset_geometry"]["buildings"][0]["Building"]["doors"]
        .as_array_mut()
        .unwrap()
    {
        door["sector_in"] = (door["sector_in"].as_u64().unwrap() + 1).into();
    }
    let mut assets = LevelAssets::new();
    let engine = construct(&serde_json::to_vec(&value).unwrap(), &mut assets);
    let grid = engine.fast_grid();
    let building = grid
        .level
        .sectors
        .iter()
        .find(|s| s.sector_type.is_building())
        .unwrap();
    assert_eq!(i16::from(building.sector_number), 5);
    assert_eq!(building.gate_indices.len(), 2);
    assert_eq!(grid.level.door_projection_infos.len(), 3);
}
