//! The fixture is generated by the editor from synthetic asset definitions.
//! No datadir, level records, profiles or sprite banks are mounted.
use robin_engine::engine::{Engine, EngineArgs, LevelAssets, LevelLoadArgs, SimConfig};
use robin_engine::level_data::LoadedLevel;

#[test]
fn map_geometry_does_not_accept_embedded_player_spawns() {
    let mut value: serde_json::Value =
        serde_json::from_slice(include_bytes!("fixtures/asset-compiled.level.json")).unwrap();
    value["spawn_player"] = true.into();
    value["spawn"] = serde_json::json!([320, 320]);
    let error = LoadedLevel::hackable_from_json(&serde_json::to_vec(&value).unwrap()).unwrap_err();
    assert!(error.contains("use a mission"), "{error}");
}

#[test]
fn geometry_warnings_do_not_require_mission_content() {
    let mut value: serde_json::Value =
        serde_json::from_slice(include_bytes!("fixtures/asset-compiled.level.json")).unwrap();
    value["asset_geometry"]["warnings"] = serde_json::json!(["Generated fragment omitted"]);
    let level = LoadedLevel::hackable_from_json(&serde_json::to_vec(&value).unwrap()).unwrap();
    assert!(level.mission.beam_mes.is_empty());
}

fn construct(bytes: &[u8], assets: &mut LevelAssets) -> Engine {
    let level = LoadedLevel::hackable_from_json(bytes).unwrap();
    assert!(level.mission.beam_mes.is_empty());
    assert!(level.mission.soldiers.is_empty());
    let mut profiles = robin_engine::profiles::ProfileManager::new();
    let mut campaign = robin_engine::campaign::Campaign::new();
    let index = campaign
        .force_next_mission_by_name(&mut profiles, "asset-test", "asset-test", true)
        .unwrap();
    campaign.current_mission_idx = Some(index);
    assets.profile_manager = std::sync::Arc::new(profiles);
    let engine = Engine::new(EngineArgs {
        campaign,
        level: LevelLoadArgs {
            assets,
            level_directory: "",
            progress: &mut |_| {},
            loaded: level,
            bg_pixel_dims: (2000., 2000.),
        },
        ground_mark_sprite: None,
        titbit_row_frame_counts: vec![],
        rng_seed: 0,
        original_rng_replay: None,
        sim_config: SimConfig {
            script_enabled: false,
            ..Default::default()
        },
    })
    .expect("construct compiled asset map without game files");
    engine
}

#[test]
fn asset_compiler_output_constructs_live_navigation_sight_and_door_links() {
    let mut assets = LevelAssets::new();
    let engine = construct(
        include_bytes!("fixtures/asset-compiled.level.json"),
        &mut assets,
    );
    let grid = engine.fast_grid();
    assert!(!grid.level.blocks.is_empty());
    assert_eq!(grid.level.door_projection_infos.len(), 1);
    assert!(!assets.environment.static_sight_obstacles.is_empty());
    assert!(
        grid.level
            .sectors
            .iter()
            .filter(|sector| !sector.gate_indices.is_empty())
            .count()
            >= 2
    );
    assert_eq!(
        assets.navigation.pathfinder_graph.static_data.move_layers[0].len(),
        2
    );
    use robin_engine::coordinates::MapPoint;
    assert!(grid.is_reachable_thin(MapPoint::new(310., 320.), MapPoint::new(370., 320.), 0));
    assert!(!grid.is_reachable_thin(MapPoint::new(330., 345.), MapPoint::new(360., 345.), 0));
}

#[test]
fn movement_clearance_opens_navigation_without_removing_sight_geometry() {
    let mut assets = LevelAssets::new();
    let engine = construct(
        include_bytes!("fixtures/asset-clearance.level.json"),
        &mut assets,
    );
    use robin_engine::coordinates::MapPoint;
    let grid = engine.fast_grid();
    assert!(grid.is_reachable_thin(MapPoint::new(330., 345.), MapPoint::new(360., 345.), 0));
    assert!(!grid.is_reachable_thin(MapPoint::new(330., 341.), MapPoint::new(360., 341.), 0));
    assert!(!assets.environment.static_sight_obstacles.is_empty());
}

#[test]
fn compiler_interchange_rejects_unresolved_asset_references() {
    let mut descriptor: serde_json::Value =
        serde_json::from_slice(include_bytes!("fixtures/asset-compiled.level.json")).unwrap();
    descriptor["asset_geometry"]["doors"][0]["sector_in"] = 65535.into();
    assert!(
        LoadedLevel::hackable_from_json(&serde_json::to_vec(&descriptor).unwrap())
            .unwrap_err()
            .contains("asset door")
    );
}

#[test]
fn non_clickable_passage_still_registers_navigation_links() {
    let mut descriptor: serde_json::Value =
        serde_json::from_slice(include_bytes!("fixtures/asset-compiled.level.json")).unwrap();
    descriptor["asset_geometry"]["doors"][0]["door_sector"]["points"] = serde_json::json!([]);
    let mut assets = LevelAssets::new();
    let engine = construct(&serde_json::to_vec(&descriptor).unwrap(), &mut assets);
    let grid = engine.fast_grid();
    assert_eq!(grid.level.door_projection_infos.len(), 1);
    assert_eq!(
        grid.level
            .sectors
            .iter()
            .filter(|s| !s.gate_indices.is_empty())
            .count(),
        2
    );
}

#[test]
fn compiled_door_retains_alternate_lock_rules() {
    let mut descriptor: serde_json::Value =
        serde_json::from_slice(include_bytes!("fixtures/asset-compiled.level.json")).unwrap();
    let door = &mut descriptor["asset_geometry"]["doors"][0];
    door["door_type"] = 7.into();
    door["locked_pc_after_patch"] = true.into();
    door["unlockable_after_patch"] = true.into();
    door["locked_npc_villain_after_patch"] = true.into();
    door["locked_npc_civilian_after_patch"] = true.into();
    let mut assets = LevelAssets::new();
    let engine = construct(&serde_json::to_vec(&descriptor).unwrap(), &mut assets);
    let mut door = engine.presentation_view().doors()[0].clone();
    assert_eq!(door.door_type, robin_engine::gate::DoorType::Trap);
    assert!(!door.locked_pc);
    door.swap_rights_patch();
    assert!(
        door.locked_pc && door.unlockable && door.locked_npc_villain && door.locked_npc_civilian
    );
    door.swap_rights_patch();
    assert!(
        !door.locked_pc
            && !door.unlockable
            && !door.locked_npc_villain
            && !door.locked_npc_civilian
    );
}

#[test]
fn sloped_asset_surface_constructs_elevation_and_navigation_holes() {
    let mut assets = LevelAssets::new();
    let engine = construct(
        include_bytes!("fixtures/asset-sloped.level.json"),
        &mut assets,
    );
    let surface = assets.environment.static_sight_obstacles.last().unwrap();
    assert!((surface.compute_top_z(320., 320.) - 10.).abs() < 0.001);
    assert!((surface.compute_top_z_from_projection(320., 310.) - 10.).abs() < 0.001);
    assert!((surface.compute_top_z_from_projection(400., 300.) - 50.).abs() < 0.001);
    use robin_engine::coordinates::MapPoint;
    let grid = engine.fast_grid();
    assert!(grid.is_reachable_thin(MapPoint::new(310., 315.), MapPoint::new(350., 295.), 0));
    // Cross the authored hole, away from the solid obstacle.
    assert!(!grid.is_reachable_thin(MapPoint::new(365., 337.5), MapPoint::new(385., 327.5), 0));
    // Cross the collision volume where it intersects the ramp.
    assert!(!grid.is_reachable_thin(MapPoint::new(330., 330.), MapPoint::new(360., 315.), 0));
}

#[test]
fn compiled_lift_registers_traversal_sector_and_both_door_links() {
    let mut assets = LevelAssets::new();
    let engine = construct(
        include_bytes!("fixtures/asset-lift.level.json"),
        &mut assets,
    );
    let grid = engine.fast_grid();
    let lift = grid
        .level
        .sectors
        .iter()
        .find(|s| s.sector_type.is_lift())
        .unwrap();
    assert_eq!(lift.lift_type, Some(robin_engine::sector::LiftType::Stairs));
    assert_eq!(lift.lift_direction, 4);
    assert_eq!(lift.gate_indices.len(), 2);
    assert_eq!(grid.level.door_projection_infos.len(), 2);
    assert_eq!(
        assets
            .navigation
            .pathfinder_graph
            .static_data
            .move_layers
            .len(),
        3
    );
}

#[test]
fn compiled_lift_rejects_dangling_and_incomplete_definitions() {
    let original: serde_json::Value =
        serde_json::from_slice(include_bytes!("fixtures/asset-lift.level.json")).unwrap();
    for field in ["motion_area_index", "lift_type", "direction"] {
        let mut bad = original.clone();
        bad["asset_geometry"]["lifts"][0][field] = 99.into();
        assert!(LoadedLevel::hackable_from_json(&serde_json::to_vec(&bad).unwrap()).is_err());
    }
    let mut missing = original;
    let mut flat = missing.clone();
    flat["asset_geometry"]["lifts"][0]["doors"][1]["point_out"][1] =
        flat["asset_geometry"]["lifts"][0]["doors"][0]["point_out"][1].clone();
    assert!(LoadedLevel::hackable_from_json(&serde_json::to_vec(&flat).unwrap()).is_err());
    missing["asset_geometry"]["lifts"] = serde_json::json!([]);
    assert!(
        LoadedLevel::hackable_from_json(&serde_json::to_vec(&missing).unwrap())
            .unwrap_err()
            .contains("no traversal definition")
    );
}

#[test]
fn lift_endpoints_are_selected_spatially_when_both_doors_use_low_actions() {
    let mut descriptor: serde_json::Value =
        serde_json::from_slice(include_bytes!("fixtures/asset-lift.level.json")).unwrap();
    descriptor["asset_geometry"]["lifts"][0]["doors"][1]["door_type"] = 5.into();
    let mut assets = LevelAssets::new();
    let engine = construct(&serde_json::to_vec(&descriptor).unwrap(), &mut assets);
    let view = engine.presentation_view();
    let doors = view.doors();
    let endpoints =
        robin_engine::gate::lift_endpoint_door_indices(doors, doors[0].sector_in).unwrap();
    assert_ne!(endpoints.0, endpoints.1);
    assert!(doors[endpoints.0 as usize].point_out.y > doors[endpoints.1 as usize].point_out.y);
}

#[test]
fn compiled_interior_registers_a_shared_building_sector() {
    let mut assets = LevelAssets::new();
    let engine = construct(
        include_bytes!("fixtures/asset-interior.level.json"),
        &mut assets,
    );
    let grid = engine.fast_grid();
    let buildings: Vec<_> = grid
        .level
        .sectors
        .iter()
        .filter(|s| s.sector_type.is_building())
        .collect();
    assert_eq!(buildings.len(), 1);
    assert_eq!(i16::from(buildings[0].sector_number), 4);
    assert_eq!(buildings[0].gate_indices.len(), 2);
    assert_eq!(grid.level.door_projection_infos.len(), 3);
}

#[test]
fn compiled_interior_rejects_invalid_entrance_identity() {
    let mut bad: serde_json::Value =
        serde_json::from_slice(include_bytes!("fixtures/asset-interior.level.json")).unwrap();
    bad["asset_geometry"]["buildings"][0]["Building"]["doors"][0]["sector_in"] = 65535.into();
    assert!(
        LoadedLevel::hackable_from_json(&serde_json::to_vec(&bad).unwrap())
            .unwrap_err()
            .contains("interior entrance")
    );
}
