"""Source-camera comparison and explicit near/far/floor corner annotations."""
import json,math
from pathlib import Path
from PIL import Image,ImageDraw
root=Path(__file__).resolve().parent;out=root/'inspection/north-corner-v10'
source=Image.open(root/'reference/mission-patches/H03_Der_MK-initial.png').convert('RGB')
data=json.loads((out/'source-correspondences.json').read_text())
fullbox=[310,1525,412,1770]
for run in data['runs']:
 name=run['name'];box={'front':[322,1550,392,1664],'return':[328,1640,412,1766]}[name]
 scale=8;size=((box[2]-box[0])*scale,(box[3]-box[1])*scale)
 raw=source.crop(box).resize(size,Image.Resampling.NEAREST);raw.save(out/(name+'-original.png'))
 overlay=raw.copy();draw=ImageDraw.Draw(overlay)
 def xy(p):return ((p[0]-box[0]+.5)*scale,(p[1]-box[1]+.5)*scale)
 colors=['cyan','#ff70ff','#ffe600'];labels=['N','F','B']
 for index,corner in enumerate(run['corners']):
  for j,p in enumerate(corner):
   x,y=xy(p);draw.ellipse((x-2,y-2,x+2,y+2),fill=colors[j]);draw.text((x+4,y-10),str(index+1)+labels[j],fill=colors[j],stroke_width=1,stroke_fill='black')
  draw.line([xy(corner[0]),xy(corner[1])],fill='cyan',width=1)
  draw.line([xy(corner[0]),xy(corner[2])],fill='#ffe600',width=1)
  if index%2:
   previous=run['corners'][index-1]
   draw.line([xy(previous[2]),xy(corner[2])],fill='#ffe600',width=1)
 overlay.save(out/(name+'-source-landmarks.png'))
 crop=((box[0]-fullbox[0])*4,(box[1]-fullbox[1])*4,(box[2]-fullbox[0])*4,(box[3]-fullbox[1])*4)
 solids=Image.open(out/'source-camera/views/view-0-solid.png').convert('RGB').crop(crop).resize(size,Image.Resampling.NEAREST)
 textured=Image.open(out/'source-camera/views/view-0-textured.png').convert('RGB').crop(crop).resize(size,Image.Resampling.NEAREST)
 panels=Image.new('RGB',(size[0]*3,size[1]+30),'#222222');d=ImageDraw.Draw(panels)
 for i,(title,img) in enumerate([('Original artwork',raw),('Actual solid geometry - source camera',solids),('Fresh source projection - same camera',textured)]):
  panels.paste(img,(size[0]*i,30));d.text((size[0]*i+8,8),title,fill='white')
 panels.save(out/(name+'-source-solid-textured.png'))
(out/'review.md').write_text('''# North wall walk — full battlement profile correction

The rejected v6 cap-only revision is replaced. Both wall arms were revisited.
There are four front openings and FIVE return openings. The fifth return gap
near the bend was missing from the earlier candidates. Each of eighteen opening
boundaries identifies its near cap corner, far cap
corner and notch-floor corner in the original artwork. Cyan is the near cap,
magenta the far cap, yellow the floor; the numbered records are in
`source-correspondences.json`. Approximate pixel uncertainty is two pixels.

## Front arm: original, actual gray model, fresh source projection

![Front source-camera comparison](front-source-solid-textured.png)

![Front explicit cap and floor landmarks](front-source-landmarks.png)

## Return arm: original, actual gray model, fresh source projection

![Return source-camera comparison](return-source-solid-textured.png)

![Return explicit cap and floor landmarks](return-source-landmarks.png)

All three columns use the original camera and identical pixel crop. The artwork
column is an unchanged nearest-neighbor enlargement. Cast shadows in the solid
use the chosen 48-degree sunlight, not copied painted shadows. Source-only texture
sampling retains the authoritative source masks; unknown surfaces remain gray.

## Geometry in eight directions

![Solid](north-48/solid.png)

![Reprojected source texture](north-48/textured.png)

The near/far wall planes are fitted jointly, with a flat crown and 20-source-pixel
opening depth. This avoids turning noisy raster corner picks into warped merlon
tops. The bent wall's two cap planes now meet at their fitted intersection.
The lower wall is retained through a fixed 190-unit boundary; this avoids the
long warped triangles seen in an intermediate trial. No detached merlon boxes
replace the complete masonry shell. The opening corners are individually
positioned, not generated by an evenly spaced array.

Review the actual solid and textured columns together. Exact agreement with
the selected observations is not claimed: the 54 labeled near/far/floor corner
residuals have 1.15-pixel RMS and 2.76-pixel maximum after imposing consistent
flat caps and parallel wall faces. This is correspondence to the manually
selected observations, not independent proof that every selected pixel is exact.
The saved mesh is closed, has positive volume and no degenerate faces; all 503
other meshes and the nine ground-footprint vertices are unchanged. A lower-wall
surface sample check found a maximum 0.095-world-unit triangulation difference.
This candidate has not been approved, synthesized, or integrated.
''')
