"""Publish a hall review candidate only after complete state and source audits."""
import json,hashlib
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];WORK=ROOT/'level-editor/work/nottingham-refinement';W=WORK/'round-42/assets/nottingham-castle-main-hall'
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def read(p):return json.loads(Path(p).read_text())
def write(p,value):Path(p).write_text(json.dumps(value,indent=2)+'\n')
def main():
 model_hash=sha(W/'model.blend');views_hash=sha(W/'modified/views.json');review=W/'inspection/independent-final-hall-review.json';ind=read(review)
 assert ind['status']=='PASS'and ind['model_sha256']==model_hash and ind['modified_views_sha256']==views_hash and ind['inspected_views']==list(range(8))
 assert read(W/'validation.json')['status']=='PASS';assert read(W/'known-rgb-validation.json')['status']=='PASS'
 lighting=read(W/'lighting-review/review.json');assert lighting['status']=='PASS'and lighting['model_sha256']==model_hash and lighting['modified_views_sha256']==views_hash
 bindings=read(W/'inspection/state-models/manifest.json');assert bindings['primary_model_sha256']==model_hash
 states=[];evidence=[review,W/'inspection/state-models/manifest.json',W/'material-states.json',W/'projection-state-layers.json',W/'inspection/source-front-final/manifest.json',W/'known-rgb-validation.json',W/'inspection/fascia-source-front-comparison.json']
 for binding in bindings['states']:
  name=binding['state'];model=Path(binding['model']);frame=Path(binding['frame_manifest']);assert sha(model)==binding['model_sha256']and sha(frame)==binding['frame_manifest_sha256'];actual=W/'inspection/actual-final'/name;audit=read(actual/'audit.json');assert audit['status']=='STRUCTURAL-PASS'and not audit['problems'];assert audit['model_sha256']==sha(model);assert read(model.parent/'known-rgb-validation.json')['status']=='PASS'
  dense=W/'inspection/source-domain'/f'{name}.json';d=read(dense);assert d['model_sha256']==model_hash and d['modified_views_sha256']==views_hash
  paths=[actual/'audit.json',actual/'materials.png',dense,W/'inspection/source-domain'/f'{name}.png',W/'inspection/source-front-final'/f'{name}-comparison.png',model.parent/'known-rgb-validation.json'];evidence.extend(paths)
  states.append({**binding,'actual_saved_material_audit':str(actual/'audit.json'),'actual_saved_material_audit_sha256':sha(actual/'audit.json'),'actual_saved_material_sheet_sha256':sha(actual/'materials.png'),'actual_saved_material_views':[{'index':i,'path':str(actual/f'view-{i}.png'),'sha256':sha(actual/f'view-{i}.png')}for i in range(8)],'dense_domain_evidence':str(dense),'dense_domain_evidence_sha256':sha(dense)})
 changes=['Restored complete original-art roof, masonry, terrace, doorway, under-eave fascia and revealed-room source ownership. Source-traced terrace497 masks and receiver-scoped neighboring tower constraints remove false foreground losses.','Stored independent covered and revealed material states on every active hall receiver; verified actual saved materials from the original source camera and all eight review directions.','Fitted the room floor and upper support to visible wall and front cut-stone contacts while preserving the lower foundation; added the missing stairside parapet, fitted the stair edge, and restored the narrow roof metal rim.']
 limits=['Reverse faces, geometry behind other assets and foundations below visible ground remain neutral. Separate spires, roofs, paving and courtyard walls retain their original source ownership.','Small flag and ridge-finial ornaments, and some fine chandelier links/braces, remain unmodeled source detail. Their artwork is not painted onto background walls. Narrow source-trace/contact fringes are individually classified in the independent census.','The room floor remains at native420; the local hearth recess and hidden upper-support transition to the preserved foundation are inferred from visible contacts. Covered and revealed views are focused inspection states, not a mission-reachability assertion.']
 candidate={'version':1,'asset_id':W.name,'status':'ready-for-user','geometry_reviewed':True,'geometry_refined':True,'inspected_views':list(range(8)),'model_sha256':model_hash,'modified_views_sha256':views_hash,'recipe':str(Path(__file__).with_name('hall_freeze_complete_revision.py')),'recipe_sha256':sha(Path(__file__).with_name('hall_freeze_complete_revision.py')),'changes':changes,'limitations':limits,'user_approval':'pending','texture_generation':'not-started','source_comparison':'inspection/source-front-final/covered-comparison.png','source_comparison_secondary':'inspection/source-front-final/revealed-comparison.png','source_rgb_validation':'known-rgb-validation.json','source_visibility_evidence':'inspection/source-domain/revealed.json','stored_material_evidence':'inspection/actual-final/covered/audit.json','independent_review':str(review.relative_to(W)),'revealed_input':'input'}
 candidate['recipe_steps']=[{'script':str(Path(__file__).with_name(name)),'sha256':sha(Path(__file__).with_name(name))}for name in ['hall_freeze_complete_revision.py','hall_eave_source_domain.py','hall_full_state_packets.py']]
 candidate['material_rebake_provenance']=read(W/'material-states.json')
 for state in ['covered','revealed']:
  for kind in ['solid','textured','context']:candidate[f'{state}_{kind}']=f'states-final/patch-008/{state}/{kind}.png'
 write(W/'candidate.json',candidate)
 actual=W/'inspection/actual-final/covered';contract={'version':1,'status':'PASS','asset_id':W.name,'model_sha256':model_hash,'modified_views_sha256':views_hash,'source_sha256':sha(W/'reference/source.png'),'source_masks_sha256':sha(W/'source-masks.json'),'inspected_views':list(range(8)),'source_visible_holes_found':False,'geometry_changed':True,'changes':changes,'gray_surface_explanation':limits,'independent_review':str(review),'independent_review_sha256':sha(review),'actual_saved_material_audit':str(actual/'audit.json'),'actual_saved_material_audit_sha256':sha(actual/'audit.json'),'actual_saved_material_sheet_sha256':sha(actual/'materials.png'),'states':states,'evidence':[{'path':str(p),'sha256':sha(p)}for p in evidence]};write(W/'source-coverage-audit.json',contract)
 (W/'review.md').write_text('# Nottingham castle main hall\n\n'+'\n'.join('- '+s for s in changes)+'\n\nBoth saved material states, all eight directions, full native449/453 domains and the complete revealed patch were independently reviewed. Known source RGB checks and frozen-workspace validation passed.\n\n'+'\n'.join('- '+s for s in limits)+'\n\nUser approval pending.\n')
 print('HALL42 READY FOR USER REVIEW',model_hash,views_hash,flush=True)
if __name__=='__main__':main()
