"""Finalize source coverage only after independent saved-image and artwork review."""
import argparse,hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];WORK=ROOT/'level-editor/work/nottingham-refinement'
def sha(path):return hashlib.sha256(path.read_bytes()).hexdigest()
def main():
 parser=argparse.ArgumentParser();parser.add_argument('asset',choices=['watchtower','northeast-spire']);a=parser.parse_args();rd=28 if a.asset=='watchtower'else 27;w=WORK/f'round-{rd}/assets/nottingham-castle-{a.asset}';review=w/'inspection/independent-source-coverage-review.json';r=json.loads(review.read_text());assert r['status']=='PASS';assert r['model_sha256']==sha(w/'model.blend');assert r['modified_views_sha256']==sha(w/'modified/views.json');assert r['inspected_views']==list(range(8))
 for filename in ['validation.json','known-rgb-validation.json']:assert json.loads((w/filename).read_text())['status']=='PASS'
 actual=w/'inspection/source-coverage-materials/audit.json';assert json.loads(actual.read_text())['status']=='STRUCTURAL-PASS';proof=json.loads((w/'projection-correction.json').read_text());assert proof['geometry_unchanged'];assert proof['geometry_before_sha256']==proof['geometry_after_sha256']
 c=json.loads((WORK/f'round-1/assets/nottingham-castle-{a.asset}/candidate.json').read_text());changes=(['Restored complete native467 watchtower shaft and walkway plus469/470 doorway, replacing black floor ownership.','Excluded actual foreground hall449 and spire445; constrained oversized spire proxy blockers to native445 after dense original-source inspection.']if a.asset=='watchtower'else['Traced foreground hall roof ridge inside native444, excluding roof artwork from the rear spire.','Restored exposed masonry behind oversized roof proxies505/506/508 with receiver-scoped original-art blocker domains.'])
 limits=(['Gray middle shaft is behind the hall roof and southeast spire; lower foundations lie behind courtyard structures. Reverse faces have no visible original artwork.']if a.asset=='watchtower'else['Gray lower-front triangle is hidden behind the foreground hall roof. Reverse faces remain unknown.'])
 c.update(status='ready-for-user',geometry_reviewed=True,geometry_refined=False,inspected_views=list(range(8)),changes=changes,limitations=limits,no_change_reason='Geometry, world transforms and faces remain exactly unchanged; only source ownership and projection were corrected.',model_sha256=sha(w/'model.blend'),modified_views_sha256=sha(w/'modified/views.json'),stored_material_evidence='inspection/source-coverage-materials/audit.json',source_comparison='inspection/source-coverage-domain.png',recipe=str(Path(__file__).with_name('audit_unseen_castle.py')),user_approval='pending',texture_generation='not-started');(w/'candidate.json').write_text(json.dumps(c,indent=2)+'\n');(w/'review.md').write_text('# '+c['asset_id']+'\n\n'+'\n'.join('- '+x for x in changes+limits)+'\n\nAll eight saved-material and review views inspected. Original-source coverage independently checked. User approval pending.\n')
 audit=dict(version=1,status='PASS',asset_id=c['asset_id'],model_sha256=c['model_sha256'],modified_views_sha256=c['modified_views_sha256'],source_sha256=sha(w/'reference/source.png'),source_masks_sha256=sha(w/'source-masks.json'),inspected_views=list(range(8)),source_visible_holes_found=False,geometry_changed=False,changes=changes,gray_surface_explanation=limits,independent_review=str(review),independent_review_sha256=sha(review),dense_domain_evidence=str(w/'inspection/source-coverage-domain.json'),dense_domain_evidence_sha256=sha(w/'inspection/source-coverage-domain.json'),actual_saved_material_audit=str(actual),actual_saved_material_audit_sha256=sha(actual),actual_saved_material_sheet_sha256=sha(actual.parent/'materials.png'),independent_source_rgb_sha256=sha(w/'known-rgb-validation.json'))
 (w/'source-coverage-audit.json').write_text(json.dumps(audit,indent=2)+'\n');proof.update(status='PASS',model_sha256=c['model_sha256'],inspected_views=list(range(8)));(w/'projection-correction.json').write_text(json.dumps(proof,indent=2)+'\n');print(w)
if __name__=='__main__':main()
