"""Finalize the source-reviewed V13 tower access-cap revision after independent QA."""
import argparse,json,hashlib
from pathlib import Path

def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 p=argparse.ArgumentParser();p.add_argument('workspace',type=Path);p.add_argument('independent_review',type=Path);a=p.parse_args();w=a.workspace.resolve();qa=json.loads(a.independent_review.read_text());assert qa['status']=='PASS';model=sha(w/'model.blend');assert qa['model_sha256']==model;assert json.loads((w/'validation.json').read_text())['status']=='PASS';assert json.loads((w/'known-rgb-validation.json').read_text())['status']=='PASS';assert json.loads((w/'inspection/access-cap-actual-mesh.json').read_text())['status']=='PASS'
 c=json.loads((w/'candidate.json').read_text());c.update(status='ready-for-user',geometry_reviewed=True,geometry_refined=True,inspected_views=list(range(8)),model_sha256=model,modified_views_sha256=sha(w/'modified/views.json'),changes=['Restored complete native tower crown, courtyard floor and lower shaft while excluding the foreground cottage and chimney.','Transferred detached gate piers349/350 to the arch under V13, retaining four tower parts.','Replaced unsupported access330 floor-to-zero column with a closed thin cap preserving the original sloped top. Actual pale source tread patches now project onto330; the taller foreground parapet328 remains a true occluder.'],limitations=['Four-unit cap thickness is inferred; hidden cap underside and reverse tower faces have no source artwork.','The original refined circular crown is preserved; source silhouette pixel mismatch at individual rear merlon corners is not treated as texture evidence for unseen surfaces.'],source_trace='inspection/access-cap-source-fit.png',independent_review=str(a.independent_review.resolve()),user_approval='pending',texture_generation='not-started')
 (w/'candidate.json').write_text(json.dumps(c,indent=2)+'\n');(w/'review.md').write_text('# '+c['asset_id']+'\n\n'+'\n'.join('- '+s for s in c['changes']+c['limitations'])+'\n\nAll eight solid, source-textured and actual saved-material views independently inspected. Exact known source RGB verified. User approval pending.\n')
if __name__=='__main__':main()
